name: Update

on:
  push:
  schedule:
    - cron: '19 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: data
      - name: Fetch
        run: |
          for f in *.json
          do
            curl -Ssf https://www.barnivore.com/$f |
              python3 -m json.tool - $f
          done
      - name: Push
        run: |
          if ! git diff --quiet --exit-code 
          then
            git config user.name GitHub Actions
            git config user.email actions@github.com
            git commit -am "Update from barnivore.com"
            git push
          fi
