name: Update

on:
  push:
  schedule:
    - cron: '19 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: data
      - name: Fetch
        run: |
          for f in beer.json liquor.json wine.json
          do
            curl -Ssf https://www.barnivore.com/$f |
              python3 -m json.tool - $f
          done
      - name: Commit
        uses: zwaldowski/git-commit-action@v1
        with:
          commit_message: Update from barnivore.com
      - name: Push
        run: git push
